version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    restart: always
    networks:
      - app_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3080"
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - DOMAIN_CLIENT=http://147.93.41.71:8080
      - DOMAIN_SERVER=http://147.93.41.71:8080
      - MONGO_URI=mongodb://mongodb:27017/librechat
    restart: always
    volumes:
      - ./.env:/app/.env
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
