version: '3.8'

services:
  api:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - type: bind
        source: ./api/app/clients/tools/manifest-additions.json
        target: /app/api/app/clients/tools/manifest-additions.json
      - type: bind
        source: ./api/app/clients/tools/.well-known
        target: /app/api/app/clients/tools/.well-known
    image: ghcr.io/danny-avila/librechat:latest  # Use production image

  nginx:
    ports:
      - "8080:80"  # Override the port in the production compose file
